### ISSUE TITLE
Why do you need to separate the last batch of the output 

### ISSUE THREAD

**Issue by vkaul11** [hsiehjackson/RULER#21]
https://github.com/hsiehjackson/RULER/blob/main/scripts/pred/call_api.py#L270 Why do you need to separate the last batch of output here and why do you need the threads above?

**Comment by hsiehjackson** [comment]
> why do you need the threads above? 

We can send multiple requests to our server in parallel. In server side, we may deal with multiple requests at the same time depends on your framework.

> why do you need to separate the last batch of output here?

We may still remain some samples because we have this [condition](https://github.com/hsiehjackson/RULER/blob/main/scripts/pred/call_api.py#L262) to join our threads.
